[build]
  command = "yarn build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"  # Changed to LTS version

[[plugins]]
package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = false
[build.processing.js]
  bundle = false
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true